package com.example.nutrip_ahealthydietapp;

import android.os.Bundle;
import android.widget.CalendarView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import java.util.HashMap;
import java.util.Map;

public class calender extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_calender);

        CalendarView calendarView = findViewById(R.id.calendarView);

        // Display current date and time
        calendarView.setDate(System.currentTimeMillis());

        // Set listener for date selection
        calendarView.setOnDateChangeListener(new CalendarView.OnDateChangeListener() {
            @Override
            public void onSelectedDayChange(@NonNull CalendarView view, int year, int month, int dayOfMonth) {
                // Get food suggestions for the selected date
                String suggestions = getFoodSuggestions(year, month, dayOfMonth);
                // Display food suggestions
                Toast.makeText(calender.this, "Selected Date: " + dayOfMonth + "/" + (month + 1) + "/" + year + "\nSuggestions: " + suggestions, Toast.LENGTH_SHORT).show();
            }
        });
    }

    private String getFoodSuggestions(int year, int month, int dayOfMonth) {
        // Example: Simple hardcoded food suggestions based on date
        Map<String, String> foodSuggestions = new HashMap<>();
        foodSuggestions.put("1/1", "Oatmeal with fruits");
        foodSuggestions.put("2/1", "Greek yogurt with honey");
        foodSuggestions.put("3/1", "Avocado toast");
        foodSuggestions.put("4/1", "Smoothie bowl");
        foodSuggestions.put("5/1", "Chia pudding with berries");
        foodSuggestions.put("6/1", "Quinoa salad with veggies");
        foodSuggestions.put("7/1", "Whole grain toast with almond butter");
        foodSuggestions.put("8/1", "Green smoothie with spinach and banana");
        foodSuggestions.put("9/1", "Egg and avocado breakfast wrap");
        foodSuggestions.put("10/1", "Fruit salad with mint");
        foodSuggestions.put("11/1", "Vegetable stir-fry with tofu");
        foodSuggestions.put("12/1", "Baked sweet potatoes with black beans");
        foodSuggestions.put("13/1", "Lentil soup");
        foodSuggestions.put("14/1", "Kale and apple salad");
        foodSuggestions.put("15/1", "Grilled salmon with asparagus");
        foodSuggestions.put("16/1", "Hummus and veggie sandwich");
        foodSuggestions.put("17/1", "Mixed nuts and dried fruit");
        foodSuggestions.put("18/1", "Greek salad with feta cheese");
        foodSuggestions.put("19/1", "Stuffed bell peppers with quinoa");
        foodSuggestions.put("20/1", "Berry and spinach smoothie");
        foodSuggestions.put("21/1", "Chicken and vegetable kebabs");
        foodSuggestions.put("22/1", "Overnight oats with chia seeds");
        foodSuggestions.put("23/1", "Shrimp and avocado salad");
        foodSuggestions.put("24/1", "Roasted chickpeas");
        foodSuggestions.put("25/1", "Turkey and cheese roll-ups");
        foodSuggestions.put("26/1", "Zucchini noodles with pesto");
        foodSuggestions.put("27/1", "Cauliflower rice stir-fry");
        foodSuggestions.put("28/1", "Beet and goat cheese salad");
        foodSuggestions.put("29/1", "Tuna salad with mixed greens");
        foodSuggestions.put("30/1", "Spaghetti squash with marinara sauce");
        foodSuggestions.put("31/1", "Cottage cheese with pineapple");
        foodSuggestions.put("1/2", "Spinach and mushroom omelette");
        foodSuggestions.put("2/2", "Grilled chicken with quinoa and veggies");
        foodSuggestions.put("3/2", "Carrot and celery sticks with hummus");
        foodSuggestions.put("4/2", "Cucumber and tomato salad");
        foodSuggestions.put("5/2", "Black bean and corn salad");
        foodSuggestions.put("6/2", "Pumpkin soup");
        foodSuggestions.put("7/2", "Peanut butter and banana sandwich");
        foodSuggestions.put("8/2", "Broccoli and cheddar soup");
        foodSuggestions.put("9/2", "Apple slices with almond butter");
        foodSuggestions.put("10/2", "Grilled shrimp with mango salsa");
        foodSuggestions.put("11/2", "Turkey and avocado sandwich");
        foodSuggestions.put("12/2", "Vegetable sushi rolls");
        foodSuggestions.put("13/2", "Chickpea salad with lemon dressing");
        foodSuggestions.put("14/2", "Blueberry and spinach smoothie");
        foodSuggestions.put("15/2", "Quinoa and black bean stuffed peppers");
        foodSuggestions.put("16/2", "Sweet potato and black bean tacos");
        foodSuggestions.put("17/2", "Roasted vegetable quinoa bowl");
        foodSuggestions.put("18/2", "Mango and black bean salad");
        foodSuggestions.put("19/2", "Eggplant parmesan");
        foodSuggestions.put("20/2", "Grilled zucchini with feta");
        foodSuggestions.put("21/2", "Farro salad with roasted vegetables");
        foodSuggestions.put("22/2", "Pineapple and chicken stir-fry");
        foodSuggestions.put("23/2", "Spinach and strawberry salad");
        foodSuggestions.put("24/2", "Salmon and avocado salad");
        foodSuggestions.put("25/2", "Poha with vegetables");
        foodSuggestions.put("26/2", "Masala oats");
        foodSuggestions.put("27/2", "Ragi dosa with chutney");
        foodSuggestions.put("28/2", "Vegetable upma");
        foodSuggestions.put("1/3", "Quinoa khichdi");
        foodSuggestions.put("2/3", "Methi thepla");
        foodSuggestions.put("3/3", "Chana masala with brown rice");
        foodSuggestions.put("4/3", "Palak paneer with whole wheat roti");
        foodSuggestions.put("5/3", "Vegetable dalia");
        foodSuggestions.put("6/3", "Bhindi masala with chapati");
        foodSuggestions.put("7/3", "Lauki (bottle gourd) sabzi with roti");
        foodSuggestions.put("8/3", "Vegetable sambar with brown rice");
        foodSuggestions.put("9/3", "Moong dal chilla");
        foodSuggestions.put("10/3", "Vegetable kadhi with brown rice");
        foodSuggestions.put("11/3", "Aloo gobi with whole wheat paratha");
        foodSuggestions.put("12/3", "Sprouted moong salad");
        foodSuggestions.put("13/3", "Rajma (kidney bean) curry with brown rice");
        foodSuggestions.put("14/3", "Stuffed baingan (eggplant) with roti");
        foodSuggestions.put("15/3", "Dhokla with green chutney");
        foodSuggestions.put("16/3", "Vegetable pav bhaji");
        foodSuggestions.put("17/3", "Cabbage poriyal with chapati");
        foodSuggestions.put("18/3", "Paneer tikka with mint chutney");
        foodSuggestions.put("19/3", "Gajar (carrot) paratha");
        foodSuggestions.put("20/3", "Mixed vegetable curry with quinoa");
        foodSuggestions.put("21/3", "Tomato rasam with brown rice");
        foodSuggestions.put("22/3", "Tindora (ivy gourd) sabzi with roti");
        foodSuggestions.put("23/3", "Beetroot and coconut sabzi with chapati");
        foodSuggestions.put("24/3", "Karela (bitter gourd) fry with roti");
        foodSuggestions.put("25/3", "Vegetable biryani with raita");
        foodSuggestions.put("26/3", "Aloo matar (potato and peas) curry with roti");
        foodSuggestions.put("27/3", "Cucumber raita with brown rice");
        foodSuggestions.put("28/3", "Mixed sprouts curry with quinoa");
        foodSuggestions.put("29/3", "Mooli (radish) paratha");
        foodSuggestions.put("30/3", "Bhindi (okra) fry with roti");
        foodSuggestions.put("31/3", "Sweet potato curry with chapati");
        foodSuggestions.put("1/4", "Vegetable jowar (sorghum) roti");
        foodSuggestions.put("2/4", "Chole (chickpeas) with brown rice");
        foodSuggestions.put("3/4", "Vegetable idli with sambar");
        foodSuggestions.put("4/4", "Arhar (toor) dal with brown rice");
        foodSuggestions.put("5/4", "Tawa paneer with roti");
        foodSuggestions.put("6/4", "Corn and methi (fenugreek) pulao");
        foodSuggestions.put("7/4", "Vegetable handvo");
        foodSuggestions.put("8/4", "Carrot and peas poriyal");
        foodSuggestions.put("9/4", "Green gram curry with brown rice");
        foodSuggestions.put("10/4", "Vegetable and paneer stew");
        foodSuggestions.put("11/4", "Dal palak (spinach dal) with roti");
        foodSuggestions.put("12/4", "Quinoa dosa with chutney");
        foodSuggestions.put("13/4", "Soya chunks curry with chapati");
        foodSuggestions.put("14/4", "Ragi mudde with sambar");
        foodSuggestions.put("15/4", "Idli with coconut chutney");
        foodSuggestions.put("16/4", "Masala dosa with sambar");
        foodSuggestions.put("17/4", "Rasam with brown rice");
        foodSuggestions.put("18/4", "Vada with sambar");
        foodSuggestions.put("19/4", "Upma with vegetables");
        foodSuggestions.put("20/4", "Pesarattu (green gram dosa)");
        foodSuggestions.put("21/4", "Avial with red rice");
        foodSuggestions.put("22/4", "Curd rice with pomegranate");
        foodSuggestions.put("23/4", "Lemon rice with peanuts");
        foodSuggestions.put("24/4", "Vegetable kootu");
        foodSuggestions.put("25/4", "Appam with vegetable stew");
        foodSuggestions.put("26/4", "Mysore bonda with coconut chutney");
        foodSuggestions.put("27/4", "Chettinad chicken with brown rice");
        foodSuggestions.put("28/4", "Kuzhi paniyaram with tomato chutney");
        foodSuggestions.put("29/4", "Puliyodarai (tamarind rice)");
        foodSuggestions.put("30/4", "Kadala curry with puttu");
        foodSuggestions.put("1/5", "Millet pongal");
        foodSuggestions.put("2/5", "Sambar sadam");
        foodSuggestions.put("3/5", "Vegetable rava dosa");
        foodSuggestions.put("4/5", "Tomato rice");
        foodSuggestions.put("5/5", "Keerai masiyal (spinach curry)");
        foodSuggestions.put("6/5", "Vegetable uthappam");
        foodSuggestions.put("7/5", "Mor kuzhambu (buttermilk curry)");
        foodSuggestions.put("8/5", "Chicken 65 with lemon rice");
        foodSuggestions.put("9/5", "Adai (lentil dosa)");
        foodSuggestions.put("10/5", "Kumbakonam kadappa (potato curry)");
        foodSuggestions.put("11/5", "Capsicum rice");
        foodSuggestions.put("12/5", "Kanchipuram idli");
        foodSuggestions.put("13/5", "Vegetable sevai (rice noodles)");
        foodSuggestions.put("14/5", "Beetroot pachadi");
        foodSuggestions.put("15/5", "Masala vada");
        foodSuggestions.put("16/5", "Kootu curry with rice");
        foodSuggestions.put("17/5", "Peerkangai (ridge gourd) kootu");
        foodSuggestions.put("18/5", "Tomato thokku with roti");
        foodSuggestions.put("19/5", "Vazhakkai (raw banana) podimas");
        foodSuggestions.put("20/5", "Mixed vegetable kurma");
        foodSuggestions.put("21/5", "Neer dosa with vegetable saagu");
        foodSuggestions.put("22/5", "Ragi mudde with avarekalu saaru");
        foodSuggestions.put("23/5", "Puli kulambu (tamarind curry)");
        foodSuggestions.put("24/5", "Methi dosa with coconut chutney");
        foodSuggestions.put("25/5", "Peas masala with appam");
        foodSuggestions.put("26/5", "Vegetable upma kozhukattai");
        foodSuggestions.put("27/5", "Karam dosa with peanut chutney");
        foodSuggestions.put("28/5", "Green gram sundal");
        foodSuggestions.put("29/5", "Paneer ghee roast with neer dosa");
        foodSuggestions.put("30/5", "Kothu parotta with egg");
        foodSuggestions.put("31/5", "Rava idli with coconut chutney");
        foodSuggestions.put("1/6", "Coconut rice with fried papad");
        foodSuggestions.put("2/6", "Vegetable idiyappam");
        foodSuggestions.put("3/6", "Pineapple rasam");
        foodSuggestions.put("4/6", "Kappa (tapioca) with fish curry");
        foodSuggestions.put("5/6", "Thakkali sadam (tomato rice)");
        foodSuggestions.put("6/6", "Carrot kosambari (salad)");
        foodSuggestions.put("7/6", "Chow chow kootu");
        foodSuggestions.put("8/6", "Onion uthappam");
        foodSuggestions.put("9/6", "Paruppu usili with beans");
        foodSuggestions.put("10/6", "Thengai sevai (coconut rice noodles)");
        foodSuggestions.put("11/6", "Spinach and dal curry");
        foodSuggestions.put("12/6", "Vangi bath (brinjal rice)");
        foodSuggestions.put("13/6", "Keerai vadai (spinach fritters)");
        foodSuggestions.put("14/6", "Kollu rasam (horse gram soup)");
        foodSuggestions.put("15/6", "Kambu koozh (pearl millet porridge)");
        foodSuggestions.put("16/6", "Pachai payaru sundal (green gram salad)");
        foodSuggestions.put("17/6", "Drumstick sambar with brown rice");
        foodSuggestions.put("18/6", "Karuveppilai (curry leaves) rice");
        foodSuggestions.put("19/6", "Jackfruit seed curry");
        foodSuggestions.put("20/6", "Mushroom pepper fry");
        foodSuggestions.put("21/6", "Pesarattu upma");
        foodSuggestions.put("22/6", "Idli upma");
        foodSuggestions.put("23/6", "Kothavarangai (cluster beans) poriyal");
        foodSuggestions.put("24/6", "Ulli theeyal (shallot curry)");
        foodSuggestions.put("25/6", "Vendakkai (okra) fry");
        foodSuggestions.put("26/6", "Ragi dosa with sambar");
        foodSuggestions.put("27/6", "Thayir vadai (curd vada)");
        foodSuggestions.put("28/6", "Poondu (garlic) kuzhambu");
        foodSuggestions.put("29/6", "Sundakkai (turkey berry) sambar");
        foodSuggestions.put("30/6", "Beans paruppu usili");
        foodSuggestions.put("1/7", "Milagu rasam (pepper soup)");
        foodSuggestions.put("2/7", "Pineapple kesari");
        foodSuggestions.put("3/7", "Capsicum bajji");
        foodSuggestions.put("4/7", "Pudina rice (mint rice)");
        foodSuggestions.put("5/7", "Inji thogayal (ginger chutney)");
        foodSuggestions.put("6/7", "Vegetable kurma with idiyappam");
        foodSuggestions.put("7/7", "Cabbage poriyal");
        foodSuggestions.put("8/7", "Avarakkai (broad beans) poriyal");
        foodSuggestions.put("9/7", "Parangikkai (pumpkin) sambar");
        foodSuggestions.put("10/7", "Aloo bonda");
        foodSuggestions.put("11/7", "Vendakkai mor kuzhambu (okra buttermilk curry)");
        foodSuggestions.put("12/7", "Sevai (rice noodles) with lemon");
        foodSuggestions.put("13/7", "Thakkali (tomato) chutney");
        foodSuggestions.put("14/7", "Kothamalli thogayal (coriander chutney)");
        foodSuggestions.put("15/7", "Kuzhi paniyaram with tomato chutney");
        foodSuggestions.put("16/7", "Cauliflower kurma");
        foodSuggestions.put("17/7", "Bitter gourd fry");
        foodSuggestions.put("18/7", "Murungakkai (drumstick) poriyal");
        foodSuggestions.put("19/7", "Karamani (cowpea) curry");
        foodSuggestions.put("20/7", "Thattai idli");
        foodSuggestions.put("21/7", "Gongura pappu (sorrel dal)");
        foodSuggestions.put("22/7", "Peerkangai (ridge gourd) chutney");
        foodSuggestions.put("23/7", "Vazhaipoo vadai (banana flower fritters)");
        foodSuggestions.put("24/7", "Kadamba sambar (mixed vegetable sambar)");
        foodSuggestions.put("25/7", "Tamarind rice with peanuts");
        foodSuggestions.put("26/7", "Tomato thokku");
        foodSuggestions.put("27/7", "Beans carrot poriyal");
        foodSuggestions.put("28/7", "Pumpkin kootu");
        foodSuggestions.put("29/7", "Ridge gourd stir-fry");
        foodSuggestions.put("30/7", "Snake gourd curry");
        foodSuggestions.put("31/7", "Rice sevai with coconut");
        foodSuggestions.put("1/8", "Cucumber pachadi");
        foodSuggestions.put("2/8", "Thayir sadam (curd rice)");
        foodSuggestions.put("3/8", "Bisi bele bath (spicy rice)");
        foodSuggestions.put("4/8", "Vegetable rava kichadi");
        foodSuggestions.put("5/8", "Tomato rice with coconut chutney");
        foodSuggestions.put("6/8", "Kara kuzhambu (spicy curry)");
        foodSuggestions.put("7/8", "Raw banana podimas");
        foodSuggestions.put("8/8", "Chow chow kootu with rice");
        foodSuggestions.put("9/8", "Vazhaithandu (banana stem) poriyal");
        foodSuggestions.put("10/8", "Morkali (rice flour upma)");
        foodSuggestions.put("11/8", "Capsicum rice with raita");
        foodSuggestions.put("12/8", "Rava upma with coconut chutney");
        foodSuggestions.put("13/8", "Chow chow poriyal");
        foodSuggestions.put("14/8", "Karamani poriyal");
        foodSuggestions.put("15/8", "Sundakkai vathal kuzhambu");
        foodSuggestions.put("16/8", "Arisi paruppu sadam (rice and dal)");
        foodSuggestions.put("17/8", "Kollu paruppu (horse gram dal)");
        foodSuggestions.put("18/8", "Vazhaipoo usili (banana flower curry)");
        foodSuggestions.put("19/8", "Vegetable stew with appam");
        foodSuggestions.put("20/8", "Mysore rasam");
        foodSuggestions.put("21/8", "Kovakkai (ivy gourd) poriyal");
        foodSuggestions.put("22/8", "Pumpkin erissery");
        foodSuggestions.put("23/8", "Potato podimas");
        foodSuggestions.put("24/8", "Vazhaikkai varuval (raw banana fry)");
        foodSuggestions.put("25/8", "Tomato rasam with rice");
        foodSuggestions.put("26/8", "Paruppu keerai (dal with spinach)");
        foodSuggestions.put("27/8", "Ragi semiya upma");
        foodSuggestions.put("28/8", "Tomato pappu");
        foodSuggestions.put("29/8", "Brinjal fry");
        foodSuggestions.put("30/8", "Cabbage vadai");
        foodSuggestions.put("31/8", "Capsicum curry");
        foodSuggestions.put("1/9", "Raw banana fry with rice");
        foodSuggestions.put("2/9", "Kothamalli podi (coriander powder)");
        foodSuggestions.put("3/9", "Puliyogare (tamarind rice)");
        foodSuggestions.put("4/9", "Sambar sadam with vegetables");
        foodSuggestions.put("5/9", "Kumbakonam kadappa");
        foodSuggestions.put("6/9", "Neer mor (buttermilk)");
        foodSuggestions.put("7/9", "Kara boondi");
        foodSuggestions.put("8/9", "Sundal (chickpea salad)");
        foodSuggestions.put("9/9", "Chayote kootu");
        foodSuggestions.put("10/9", "Chitranna (lemon rice)");
        foodSuggestions.put("11/9", "Tomato biryani with raita");
        foodSuggestions.put("12/9", "Murungai keerai (drumstick leaves) poriyal");
        foodSuggestions.put("13/9", "Morkuzhambu (buttermilk curry) with rice");
        foodSuggestions.put("14/9", "Kara kuzhambu with vegetables");
        foodSuggestions.put("15/9", "Kothu chapati with vegetables");
        foodSuggestions.put("16/9", "Methi thepla");
        foodSuggestions.put("17/9", "Ragi rotti with chutney");
        foodSuggestions.put("18/9", "Tomato chutney with dosa");
        foodSuggestions.put("19/9", "Mooli paratha with curd");
        foodSuggestions.put("20/9", "Pesarattu with ginger chutney");
        foodSuggestions.put("21/9", "Vegetable upma with coconut chutney");
        foodSuggestions.put("22/9", "Lemon sevai");
        foodSuggestions.put("23/9", "Kuzhi paniyaram with mint chutney");
        foodSuggestions.put("24/9", "Keerai masiyal with rice");
        foodSuggestions.put("25/9", "Kadamba sambar with brown rice");
        foodSuggestions.put("26/9", "Vegetable pongal with sambar");
        foodSuggestions.put("27/9", "Sundal with chickpeas");
        foodSuggestions.put("28/9", "Tomato thokku with chapati");
        foodSuggestions.put("29/9", "Pineapple kesari with rava");
        foodSuggestions.put("30/9", "Kambu koozh with butter milk");
        foodSuggestions.put("1/10", "Cabbage poriyal with coconut");
        foodSuggestions.put("2/10", "Beans carrot poriyal with roti");
        foodSuggestions.put("3/10", "Ridge gourd stir-fry with chapati");
        foodSuggestions.put("4/10", "Snake gourd curry with rice");
        foodSuggestions.put("5/10", "Rice sevai with lemon");
        foodSuggestions.put("6/10", "Cucumber pachadi with curd");
        foodSuggestions.put("7/10", "Thayir sadam with pomegranate");
        foodSuggestions.put("8/10", "Bisi bele bath with raita");
        foodSuggestions.put("9/10", "Vegetable rava kichadi with sambar");
        foodSuggestions.put("10/10", "Tomato rice with papad");
        foodSuggestions.put("11/10", "Kara kuzhambu with drumstick");
        foodSuggestions.put("12/10", "Raw banana podimas with rice");
        foodSuggestions.put("13/10", "Chow chow kootu with chapati");
        foodSuggestions.put("14/10", "Vazhaithandu poriyal with rice");
        foodSuggestions.put("15/10", "Morkali with chutney");
        foodSuggestions.put("16/10", "Capsicum rice with curd");
        foodSuggestions.put("17/10", "Rava upma with chutney");
        foodSuggestions.put("18/10", "Chow chow poriyal with rice");
        foodSuggestions.put("19/10", "Karamani poriyal with chapati");
        foodSuggestions.put("20/10", "Sundakkai vathal kuzhambu with rice");
        foodSuggestions.put("21/10", "Arisi paruppu sadam with papad");
        foodSuggestions.put("22/10", "Kollu paruppu with rice");
        foodSuggestions.put("23/10", "Vazhaipoo usili with roti");
        foodSuggestions.put("24/10", "Vegetable stew with rice");
        foodSuggestions.put("25/10", "Mysore rasam with papad");
        foodSuggestions.put("26/10", "Kovakkai poriyal with rice");
        foodSuggestions.put("27/10", "Pumpkin erissery with chapati");
        foodSuggestions.put("28/10", "Potato podimas with roti");
        foodSuggestions.put("29/10", "Vazhaikkai varuval with rice");
        foodSuggestions.put("30/10", "Tomato rasam with chapati");
        foodSuggestions.put("31/10", "Paruppu keerai with rice");




        // Add more suggestions as needed

        String key = dayOfMonth + "/" + (month + 1);
        return foodSuggestions.getOrDefault(key, "Salad with grilled chicken");
    }
}
